//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvisFormations.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avis
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public double Note { get; set; }
        public int IdFormation { get; set; }
        public System.DateTime DateAvis { get; set; }
        public string UserId { get; set; }
        
        public Formation Formation { get; set; }
    }
}
